### ISSUE TITLE
V10 Compatibility 

### ISSUE THREAD

**Issue by morgan613** [trev33b/dice-tooltip2#10]
Hi! First off thank you for your work on this awesome module! The module currently works in v10 but triggers a bunch of deprecation warnings, which I believe will eventually mean this module will become incompatible with future foundry versions. I was wondering if there is a plan to update this module with foundry's new way of referencing certain things?

**Comment by trev33b** [comment]
Thanks for filing this issue.

Yes.  I just happened to have installed v10 today to see how well dice-tooltip works.  I noticed the same thing regarding the deprecations and yes I'll start looking at this.  

It will likely take me a week or two to sort through all of the errors because the code is heavily dependent these types of references and changes to the dnd5e system code (which I expect to have changed since I last did this).

In addition to the deprecations, I also noticed that some of the tooltips are completely broken (such as the one for short rest).

**Comment by morgan613** [comment]
Wonderful!! Thank you very much, I love this module for in-person play!

**Comment by infias** [comment]
def looking forward to this getting fixed for v10

**Comment by trev33b** [comment]
Version 2.4.0 is now released which works with FoundryVTT 10.  This version will NOT work with FoundryVTT 9.

CC: @morgan613 @infias
